#ifndef CONSTANTS_H_
#define CONSTANTS_H_

const int SUBPIXELS_LOG2 = 3;
const int PRIMITIVE_RIGHT_MAJOR_BIT = (1 << 0);

const int MAX_PRIMITIVES = 0x4000;
const int TILE_BINNING_STRIDE = MAX_PRIMITIVES / 32;
const int TILE_BINNING_STRIDE_COARSE = TILE_BINNING_STRIDE / 32;
const int MAX_WIDTH = 2048;
const int MAX_HEIGHT = 2048;
const int TILE_WIDTH = 8;
const int TILE_HEIGHT = 8;
const int MAX_TILES_X = MAX_WIDTH / TILE_WIDTH;
const int MAX_TILES_Y = MAX_HEIGHT / TILE_HEIGHT;
const int MAX_TILES_X_LOW_RES = MAX_WIDTH / (4 * TILE_WIDTH);
const int MAX_TILES_Y_LOW_RES = MAX_HEIGHT / (4 * TILE_HEIGHT);
const int RASTER_ROUNDING = (1 << (SUBPIXELS_LOG2 + 16)) - 1;
const int TILE_INSTANCE_STRIDE = 0x10000;
const int MAX_RENDER_STATES = 1024;

#endif